CI update and Custom client class
doofinder/pydoof pull request #41
Opened 2024-04-05 08:27 UTC by sonic182

More flexible client

2024-04-05 09:36 UTC, sonic182 commented on pydoof/search_api/internals.py
> -from pydoof.search_api.api_client import SearchAPIClient
This is very old stuff that is not used anymore

2024-04-05 11:08 UTC, Almogo97 approved these changes
Some nice ruff action going on here! :+1:

2024-04-05 11:08 UTC, Almogo97 commented on .github/workflows/ci.yml
> +        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
```suggestion
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
```
The adhd

2024-04-05 11:19 UTC, Almogo97 requested changes
Ok hold up. Never mind I don't like this. Please make 2 PRs when your refactoring, one for the introduction of ruff/ci and the other for the client changes.

I don't like how you have to pass the client to each function and how there's a default. I don't see myself passing a client each time I need to make a call to the library. It should be an instance of the client the one that has the methods, not vice-versa.

Also can you explain why the need to inject the client now? I don't see an explanation nor there's an issue attached. Also having a default client instantiated each time also smells a little odd.

2024-04-05 11:31 UTC, Almogo97 approved these changes
Ok, I've seen that the client was already being created inside the function. Sry though those changes were also introduced in this PR. Still don't like it but since it's been working like that forever...

Still an explanation on why injecting the client now would be nice.

2024-04-08 07:32 UTC, sonic182 commented
> Ok, I've seen that the client was already being created inside the function. Sry though those changes were also introduced in this PR. Still don't like it but since it's been working like that forever...
> 
> Still an explanation on why injecting the client now would be nice.

I needed to update the base headers that the base class has, to send more headers in the api calls.

The client has been like this since long while, the thing would be to make a major refactor if any may want it...

2024-04-08 07:33 UTC, sonic182 commented on .github/workflows/ci.yml
> +        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
This change makes CI to test python 3.1

2024-04-08 07:59 UTC, mjosecuchillo reviewed
Añade algún tipo de documentación en algún sitio, en el README aunque sea. Comenta las especificaciones básicas que debe tener ese cliente (que debe heredar de APIClient o lo que sea) para no tener que mirar el código y saber que funciona internamente haciendo `client.get`, `client.post `y no `('GET', url)`... por ejemplo

2024-04-08 08:10 UTC, sonic182 commented
> Añade algún tipo de documentación en algún sitio, en el README aunque sea. Comenta las especificaciones básicas que debe tener ese cliente (que debe heredar de APIClient o lo que sea) para no tener que mirar el código y saber que funciona internamente haciendo `client.get`, `client.post `y no `('GET', url)`... por ejemplo

Eso debería ser una documentación tipo [sphinxdocs](https://www.sphinx-doc.org/en/master/) que te auto genere algo así https://aiosonic.readthedocs.io/en/latest/reference.html (usando readthedocs por ejemplo, o CI)

Con solo documentar las clases ya se pudiera, pero lo veo más para otro PR

2024-04-08 08:12 UTC, mjosecuchillo commented
> > Añade algún tipo de documentación en algún sitio, en el README aunque sea. Comenta las especificaciones básicas que debe tener ese cliente (que debe heredar de APIClient o lo que sea) para no tener que mirar el código y saber que funciona internamente haciendo `client.get`, `client.post `y no `('GET', url)`... por ejemplo
> 
> Eso debería ser una documentación tipo [sphinxdocs](https://www.sphinx-doc.org/en/master/) que te auto genere algo así https://aiosonic.readthedocs.io/en/latest/reference.html (usando readthedocs por ejemplo, o CI)
> 
> Con solo documentar las clases ya se pudiera, pero lo veo más para otro PR

Pero no me refiero a una documentación tan extensa de momento. Algo que te diga que puedes pasar un cliente y no usar el de por defecto

2024-04-08 09:35 UTC, mjosecuchillo approved these changes

2024-04-08 09:39 UTC, merged